name = "worker-mailgun-telegram"
main = "src/index.ts"
compatibility_date = "2023-04-17"
account_id = "96d18c881e62ba88acd99585849442ae"

# Imposta la versione di Node.js compatibile
compatibility_flags = ["nodejs_compat"]

# Configurazione per l'ambiente di sviluppo
[dev]
port = 8787

# Variabili d'ambiente (aggiungi qui le tue variabili segrete)
[vars]
# BOT_TOKEN = ""
# CHAT_ID = ""

# Configurazione per il deployment del worker
# Se vuoi pubblicare su workers.dev
workers_dev = true

# Se vuoi usare un dominio personalizzato, rimuovi il commento e configura queste righe
# [[routes]]
# pattern = "mailgun-webhook.tuodominio.com/*"
# zone_id = ""

[triggers]
crons = []